### ISSUE TITLE
SERVER_SELECTION_TIMEOUT_MS dive twice

### ISSUE THREAD

**Issue by bluethon** [dcrosta/flask-pymongo#107]
https://github.com/dcrosta/flask-pymongo/blob/1b310a5e8579859f4ad8679703d3afb19a19a66e/flask_pymongo/__init__.py#L132

This parse func will use pymongo's validate func for the timeout number, but in pymongo, it will use it  too, so, if I set this value=5000(I want 5s), in the end, mongo client use the value = 0.005(s)
- flask-pymongo==0.5.1
- pymongo==3.6.1

**Comment by dcrosta** [comment]
HI @bluethon, thanks for the report. I'm planning a pretty big overhaul of Flask-PyMongo in the nearish future, which will simplify and address this issue. Please see #110 for the news & discussion.
