### ISSUE TITLE
Providing URI could overwrites options with defaults

### ISSUE THREAD

**Issue by asahaf** [dcrosta/flask-pymongo#108]
Providing URI option overwrites options with default values when the options are not provided in the URI itself but set as individual settings. When you set 'MONGO_CONNECT', for exmaple, to 'False' but you didn't provide the 'connect' option in the URI, it will overwrite 'MONGO_CONNET' with 'True' even thought it was set to 'False'

**Comment by dcrosta** [comment]
HI @asahaf, thanks for the report. I'm planning a pretty big overhaul of Flask-PyMongo in the nearish future, which will simplify and address this issue. Please see #110 for the news & discussion.

**Comment by asahaf** [comment]
Thanks @dcrosta
