### ISSUE TITLE
Why Flask-PyMongo bulk_writes method doesn't exist?

### ISSUE THREAD

**Issue by Greilachelous** [dcrosta/flask-pymongo#112]
I have some code snippet like this:

    from flask import Flask
    from flask_pymongo import PyMongo
    from pymongo import InsertOne, UpdateOne, DeleteOne, ReplaceOne
    from flask import jsonify
    
    app = Flask(__name__)
    app.config['MONGO_DBNAME'] = 'MyDB'
    
    mongo = PyMongo(app)
    coll = mongo.db['collection1']
    
    requests = []
    for d in data_to_delete:
        requests.append(DeleteOne({'key1': d}))
    
    result = coll.bulk_writes(requests)

    return jsonify(result=result.deleted_count)

When I try to execute it, I get the error message:

    TypeError: 'Collection' object is not callable. If you meant to call the 'bulk_writes' method on a 'Collection' object it is failing because no such method exists.

[PyMongo documentation][1] says that `Collection` object has this method, though I know that `Flask-Pymongo` is a wrapper around `PyMongo`.
What could be the problem, and how could I use `bulk_writes()` with `Flask-Pymongo` collections?

Thank you for your help!

ubuntu 16.04 LTS
Werkzeug==0.14.1
Flask==1.0.2
Flask-PyMongo==0.5.2
pymongo==3.6.1

  [1]: http://api.mongodb.com/python/current/api/pymongo/collection.html

**Comment by dcrosta** [comment]
For future finders of this, I posted an answer at https://stackoverflow.com/a/51135364/124745
