### ISSUE TITLE
Import Error in virtual environment

### ISSUE THREAD

**Issue by vbansal027** [dcrosta/flask-pymongo#115]
Unable to import flask_pymongo even after successful installation in a virtual environment, set up for a flask app.
![image](https://user-images.githubusercontent.com/20636236/44446949-4b683280-a604-11e8-8778-ae3bcc457da1.png)
![image](https://user-images.githubusercontent.com/20636236/44446983-663aa700-a604-11e8-8b5b-43fe6b13564e.png)

**Comment by vbansal027** [comment]
Yes, I can successfully import at the command line in my virtualenv. But, the error persists while doing so in the VSCode. I do not have any logs for the same either

**Comment by dcrosta** [comment]
OK. You should report this to the VSCode team, or try asking on StackOverflow — it sounds like Flask-PyMongo itself is installed and working properly.
