### ISSUE TITLE
Authentication issue via app.config

### ISSUE THREAD

**Issue by george-gssy** [dcrosta/flask-pymongo#116]
Hello,

Fedora 28
Pymongo: 3.7.1
Flask-pymongo: 2.0.1

I can't find the way, how to authenticate my app's access to a mongodb database.
I tried to as follows:
```
app.config['MONGO_USERNAME'] = 
app.config['MONGO_PASSWORD']  =
etc.
```
like I saw in some examples on Stackoverflow and elsewhere, but no success.
The I found in the flask-pymongo code:

> Flask-PyMongo no longer accepts many of the configuration variables
>        it did in previous versions. You must now use a MongoDB URI to
>        configure Flask-PyMongo.

Then I've read a bit into some of github's discussion regarding this topic, so I am a bit confused now, how to do it.
What is the preferred way to do the authentication between flask and mongoDB server?
Thank you.

**Comment by george-gssy** [comment]
O.K. Meanwhile I've found the way I guess: 
I pass all the arguments via a single URI string, which solution I've dug from one of the mongoDB documentation.
Please confirm if it is the way, as I didn't find in the flask-pymongo docs(maybe my bad).
Thank you!

**Comment by dcrosta** [comment]
Hi --

As of Flask-PyMongo 2.0, the only way to configure MongoDB is via a MongoDB URI. This includes authentication and all other parameters. You can read about this more in #110 if you like.

Unfortunately there are probably a bunch of out-of-date answers floating around on StackOverflow and the like. You could help the community by offering comments or updates to those answers so that others can avoid the frustration you ran into just now.

Thanks!

**Comment by george-gssy** [comment]
Hi,
Thank you for your quick response. I will try to help the others to find the way out of some traps of kind of these, as I can.
Thanks.
PS: Anyway, can you give me a brief answer as the maintainer, why does it mean a help for an ordinary flask user to use flask-pymongo on top of pymongo, I guess not just for the helpers?

**Comment by dcrosta** [comment]
Yeah, the helpers are the reason you'd use Flask-PyMongo. The goal was (and is) to add more. In particular there's a lot of room for improvements around JSON handling, and potential for integration with other Flask extensions (eg for session storage, caching, things like that).

**Comment by george-gssy** [comment]
Thanks for the answers!
