### ISSUE TITLE
Add example for multiple databases

### ISSUE THREAD

**Issue by jaybo** [dcrosta/flask-pymongo#118]
I have a massive confusion regarding multiple databases.  Do I need Eve?  flask-pymongo?  Something else?

All I want is to have a single endpoint switch between multiple databases.  Examples on stackoverflow mention that its not supported in Eve:
    https://stackoverflow.com/questions/39249272/multiple-databases-with-eve

Or that you need to use authentication:
    https://stackoverflow.com/questions/51364424/python-eve-mongodb-read-from-multiple-mongodb-databases

Now, onto flask-pymongo.  The documentation shows how to initialize multiple databases, but not how to set up the endpoint to switch between them.  Maybe adding this as a simple example would be useful for us neophytes.

I'm looking for both of these using the same route and somehow switching to the correct database:
    http://localhost:27017/myDatabase1/user
    http://localhost:27017/myDatabase2/user

**Comment by dcrosta** [comment]
There's no notion of "switching" databases, as there's no notion of a "current" database or anything like that. Each `PyMongo` instance usually addresses a single MongoDB database, but you can have more than one (you would just initialize each one with a separate URI); or you can access any database on the same MongoDB server by using the `cx` attribute (the connection, a `MongoClient`) to access the other databases, just like you would when using PyMongo directly.

If your databases require authentication, you must use the first option -- a separate `PyMongo` instance per database -- as authentication is a per-session (per connection) notion in MongoDB. You can read more in the description of the deprecated `authenticate()` method: http://api.mongodb.com/python/current/api/pymongo/database.html#pymongo.database.Database.authenticate

**Comment by dcrosta** [comment]
Then you can connect once to your MongoDB server (you can use a connection string without any database name, as of 2.2.0, released last week). You can access each database through the `cx` attribute. Suppose you have 2 databases, `experiment1` and `experiment2`, then you can do:

```python
mongo = PyMongo(...)

exp1 = mongo.cx["experiment1"]  # the first database
exp2 = mongo.cx["experiment2"]  # the second database
```

and so on.

Basically, the things you can do with PyMongo by itself you can do with Flask-PyMongo, since it's a pretty thin wrapper on top of the underlying driver.

Does this help clarify things?

**Comment by jaybo** [comment]
The mists are slowly parting.  So I should do something like:

    @app.route('/<database>/foo')
    def foo(database):
        db = mongo.cx[database]  
        foo_data = db.foo.find({'whatever'}]
        ...

**Comment by jaybo** [comment]
Thanks much for your help.  I found something that seems to work. Please let me know if there's a more elegant solution.

    # create a dict of known databases
    databases = {
        'Z100': mongo.cx['Z100'],
        'Z101': mongo.cx['Z101'],
    }

    @app.route("/<database>/foo1")
    def foo1(database):
        db = databases[database] # fetch the appropriate DB
        data = db.tar.find_one({'metadata.grid' : {'$eq': '5000'}})
        print(database + str(len(data)))
        return 'foo1 ' + database + str(len(data))

**Comment by dcrosta** [comment]
Yup, that'll work, too.
