### ISSUE TITLE
Unexpected keyword argument 'lifetime'

### ISSUE THREAD

**Issue by joackobengochea** [dcrosta/flask-pymongo#133]
The dependency for pymongo lib is set as ">=3.5", causing the installation of the latest version of pymongo, in particular, the version 3.9.0, in which the argument 'lifetime' of a query() function was deleted. This causes the following crash: 
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pymongo/srv_resolver.py", line 73, in _resolve_uri
    lifetime=self.__connect_timeout)
TypeError: query() got an unexpected keyword argument 'lifetime'
```
I'll open a PR fixing the version ASAP :)

**Comment by 7i11** [comment]
Hello!, you can see commit [here](https://github.com/mongodb/mongo-python-driver/commit/62400e548db8e02e82afa77b9014d21e47ed2f7c)

**Comment by dcrosta** [comment]
Closing per discussion in #134

**Comment by stsmith1991** [comment]
it still return 

pymongo.errors.ConfigurationError: query() got an unexpected keyword argument 'lifetime'

P.S. first install dnspython3, then uninstall dnspython, then install dnspython=2.1
![2021-04-30_00-56-37](https://user-images.githubusercontent.com/38431753/116610760-fd786080-a94e-11eb-87f6-f12f2167df9d.png)
![2021-04-30_00-56-09](https://user-images.githubusercontent.com/38431753/116610762-fea98d80-a94e-11eb-8458-d0e8250df2b7.png)

.0
