### ISSUE TITLE
tox command failing on x86_64 and arm64

### ISSUE THREAD

**Issue by odidev** [dcrosta/flask-pymongo#157]
I have been working on installing and testing flask-pymongo package for x86_64 and arm64 architectures on my local server. While testing this package using ```tox –e py38``` I am getting the below error. It would be really helpful if you could share some pointers on it. 

```AssertionError: too many tox-docker mongo port env vars (found 0)```

**Test output at x86_64:** [test_flaskpymongo_x86_py38.txt](https://github.com/dcrosta/flask-pymongo/files/8160272/test_flaskpymongo_x86_py38.txt)
**Test output at arm64:** [test_flaskpymongo_arm64_py38.txt](https://github.com/dcrosta/flask-pymongo/files/8160271/test_flaskpymongo_arm64_py38.txt)

**Comment by odidev** [comment]
@dcrosta Is there any update for the above issue?

**Comment by dcrosta** [comment]
There's no tox environment `py38`. Flask-PyMongo uses tox a little differently, specifically, it uses tox to manage the testing matrix of pymongo, flask, and mongodb versions (via tox-docker). Your tests will run in whatever python you invoke `tox` with. Check `tox -l` for a list of environments we test with.

(In CI, we test will all supported Python versions, as well, but not typically on local machines, at least I haven't been).

**Comment by dcrosta** [comment]
> E ImportError: cannot import name 'json' from 'itsdangerous'

This is resolved in flask > 1.1.4, I guess flask 1.0 is abandoned at this point. I'll accept a pull request to remove it from the test matrix

> E ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

This probably should be reported against Jinja, if they still support Jinja 2.x. If they don't, then we should remove Flask 1.1 from the test matrix as well.

> AttributeError: 'TestenvConfig' object has no attribute '_docker_containers'

I don't get this error in the [official azure pipeline](https://dev.azure.com/dcrosta/flask-pymongo/_build?definitionId=2&_a=summary) ... I don't know what you're configured differently. Probably it means that either the `docker` python module isn't installed or docker itself isn't installed or working.

Why are you trying to set up CI for flask-pymongo anyway?
