### ISSUE TITLE
Add support for the authentication source parameter

### ISSUE THREAD

**Issue by rspeed** [dcrosta/flask-pymongo#34]
To prevent the duplication of authentication data across databases, MongoDB has two mechanisms to delegate authentication to a specific separate database. Both use a specific key in the `system.users` collection, but act in the opposite direction. The first method is the `otherDBRoles` key in the `admin` database. The value names both the table that receives authentication and the roles assigned to the user. The other method is the `userSource` key, which goes in any database and simply refers to another database with the same user.

For both methods, when the client authenticates, it has to do so against the _other_ database – `admin` for the first method, the named DB in the other. To accomplish this in PyMongo, a `source` parameter is included when calling `MongoDB.authenticate`.

Adding support for this feature should be fairly straightforward. IT requires the addition of a new config value with a name like `PREFIX_SOURCE`, as well as parsing the `authSource` URI parameter. That value is then passed to the authentication method, and that's all there is to it.

**Comment by blade2005** [comment]
@rspeed did you ever come up with a way around this? Obviously this wasn't implemented and seeing as how it's been open for over 3 years at this point I doubt it will be.

**Comment by rspeed** [comment]
Nah, I don't even remember what I was using this for.

**Comment by tcco** [comment]
Quite unfortunate this is not an added feature. Here is the workaround.

Order of operations:
Instantiate flask_pymongo.PyMongo, lets call the var mongo
Call mongo.init_app(application, config_prefix=application.config['MONGO_CONFIG_PREFIX'])
Under app_context, run mongo.db.authenticate(user, pwd, source='source_db')

Not ideal, would appreciate a cleaner solution.

**Comment by dcrosta** [comment]
#88 fixed this, and will be released as part of the upcoming 0.5.0 release.
