### ISSUE TITLE
lack support for ssl

### ISSUE THREAD

**Issue by kapilt** [dcrosta/flask-pymongo#37]

**Comment by blade2005** [comment]
I'm working on this in a branch. I know this is an old issue but it is something I was working on when i was using flask and mongodb

**Comment by dcrosta** [comment]
HI @kapilt and @blade2005 -- I'm planning a pretty big overhaul of Flask-PyMongo in the nearish future, which will simplify and address this issue. Please see #110 for the announcement & discussion.
