### ISSUE TITLE
pass uri directly instead of trying to parse every option back out for merge.

### ISSUE THREAD

**Issue by kapilt** [dcrosta/flask-pymongo#38]
the parsing and merge with the uri, creates a situation where this integration will always struggle to keep up with the latest features and capabilities, it should ideally just pass through and then pass purely config driven options separately (document_class).

**Comment by dcrosta** [comment]
Yup, you got it right @kapilt. Please see #110 for an announcement & discussion on the future of Flask-PyMongo (tldr: it'll be a lot like what you request here)
