### ISSUE TITLE
setup.py setup_requires=['nose'] prevents offline installation.

### ISSUE THREAD

**Issue by kapilt** [dcrosta/flask-pymongo#39]
this line prevents offline install via pip. the documented way to do offline installs for pip is to capture all deps to a dir and then to install from them ala

pip install -d tools/dist -r requirements.txt
pip install --no-index --find-links=file://$PWD/tools/dist -r requirements.txt

the flask-pymongo setup_requires attempts to resolve and install nose, even if it is already installed and won't pick it up. yes this is a distribute/setuptools bug, but removing this line and everything works and afaics this declaration isn't even true.

**Comment by dcrosta** [comment]
Closed by #53
