### ISSUE TITLE
URI parsing is incorrect

### ISSUE THREAD

**Issue by heichwald** [dcrosta/flask-pymongo#40]
Looks like _ is wrong in the name of the parameters.
            print parsed['options'].get('readpreference')
            print parsed['options'].get('replicaset')

Gives me values but the code uses replica_set, read_preference which prints None

{'username': None, 'nodelist': [('mongo02', 27017), ('mongo03', 27017)], 'database': 'articles', 'collection': None, 'password': None, 'options': {'readpreference': 2, 'replicaset': 'rs0'}}

thorugh MONGO_URI='mongodb://mongo02,mongo03/articles?replicaSet=rs0&readPreference=secondary'

**Comment by dcrosta** [comment]
Fixed in #86.
