### ISSUE TITLE
MongoClient write concern parameters

### ISSUE THREAD

**Issue by jyxt** [dcrosta/flask-pymongo#41]
Could you add MongoClient's 'write concern options' to init_app?
http://api.mongodb.org/python/current/api/pymongo/connection.html
I can try a pull.

**Comment by Garito** [comment]
+1

**Comment by dcrosta** [comment]
HI @jyxt -- I'm planning a pretty big overhaul of Flask-PyMongo in the nearish future, which will simplify and address this issue. Please see #110 for the announcement & discussion.
