### ISSUE TITLE
http://127.0.0.1:5000/HomePage

### ISSUE THREAD

**Issue by DavidAwad** [dcrosta/flask-pymongo#44]
Messes with my flask apps! 
Every time  i run any app and try to navigate to http://127.0.0.1:5000/ 
it changes it to http://127.0.0.1:5000/HomePage

I'm not even using this app anymore I'm trying to use other flask apps that were working before.

**Comment by dcrosta** [comment]
Closed by #51 -- @DavidAwad thanks for the patch and bug report, and I'm really ashamed it took almost 3 years to get to this, I've been horrible to this project.

**Comment by shaikat99** [comment]
i am also getting the same issue .you can run it on other browsers as it will work over there.

**Comment by RAHULJAIN1000** [comment]
goi kah

**Comment by yoneslak** [comment]
app = Flask(__name__)
 
@app.route('/user/<username>')
def show_user_profile(username): 
    # show the user profile for that user
    return (f'User {username}')
    
@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return (f'Post {post_id}')
    
@app.route('/path/<path:subpath>')
def show_subpath(subpath):
    # show the subpath after /path/
    return (f'Subpath {subpath}')

**Comment by putcists** [comment]
when i run http://127.0.0.1:5000/ i am get this error Error occurred in request., ReadTimeout: HTTPSConnectionPool(host='lovakumari001.cognitiveservices.azure.com', port=443): Read timed out. (read timeout=100)

**Comment by arsenalarsena** [comment]
http://127.0.0.1:5000/api/articles
