### ISSUE TITLE
Cannot use multiple replicaset instances which run on different ports

### ISSUE THREAD

**Issue by markunsworth** [dcrosta/flask-pymongo#46]
It's not possible to use the _HOST config key with port numbers included because the host and port values are being [concatenated](https://github.com/dcrosta/flask-pymongo/blob/master/flask_pymongo/__init__.py#L168). 

This is particularly problematic when using several seeds to connect to a replicaset:

    MONGO_HOST='morton.local:30000,morton.local:30001,morton.local:30002'

The better way to do this is to pass the port number to the pymongo connection class (mongoclient or mongoreplicaset client) and leave pymongo to decide on whether to use the port

**Comment by dcrosta** [comment]
Closed in  #49
