### ISSUE TITLE
Support Python 3.4

### ISSUE THREAD

**Issue by davide-ceretti** [dcrosta/flask-pymongo#56]
Flask-PyMongo is compatible with and tested on Python 2.6, 2.7, and 3.3. It should be nice to have it compatible and tested on Python 3.4 as well.

**Comment by dcrosta** [comment]
Flask-PyMongo 0.3.1 (soon to be released to the Cheese Shop) is now tested on Py3.4 in Travis -- see https://travis-ci.org/dcrosta/flask-pymongo/jobs/57809695.
