### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by croshchupkin** [dcrosta/flask-pymongo#60]
Could you please add an explicit LICENSE file to the repository?
I'm working on a project for Cisco, and their internal tool that is used for describing assets used in projects requires that you add a text of the license for open-source components.

**Comment by dcrosta** [comment]
@croshchupkin sure thing, sorry this took a while to get around to. Do you need me to cut a new release into PyPI, or is github master having a LICENSE sufficient?

The license is 2-clause BSD, by the way.

**Comment by croshchupkin** [comment]
I think I'll just go with the License file from the master. I already created a component with the current version in the Cisco's tool, so I don't really want to create a new one.

Thanks.
