### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by spitzbubchen** [dcrosta/flask-pymongo#61]
You show some DB search examples on https://flask-pymongo.readthedocs.org/en/latest/, however, it would be nice to see some examples on how to create/insert a Document.

Sorry for sounding naive, but I'm completely new to NoSQL, and I'm use to SQLAlchemy and model representation. I guess things are different here... Since flask-pymongo was the first to pop up when Googling "flask mongodb" it is likely that more MongoDB beginners will be coming here to learn how to use MongoDB with Flask. For example, how would one create a model such as this:

	class Post(db.Document):
		created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
		title = db.StringField(max_length=255, required=True)
		slug = db.StringField(max_length=255, required=True)
		body = db.StringField(required=True)
		comments = db.ListField(db.EmbeddedDocumentField('Comment'))

**Comment by dcrosta** [comment]
Flask-PyMongo doesn't have an ORM-like layer, it's just a thin wrapper on PyMongo. You should check out [the PyMongo Tutorial](http://api.mongodb.org/python/2.8/tutorial.html) for more info on how to insert/query/update/delete, and also see the [the MongoDB docs](http://docs.mongodb.org/).

Alternately, you might want to look at [MongoEngine](http://mongoengine.org/) which looks and feels more like the Django ORM, and might be more familiar to you. It doesn't have any particular integration with Flask-PyMongo, but you don't need Flask-PyMongo to use MongoDB and Flask together.

**Comment by spitzbubchen** [comment]
Some excellent pymongo examples can be found here:
http://docs.mongodb.org/ecosystem/use-cases/
Maybe a link on the flask-pymongo homepage would help direct users.
