### ISSUE TITLE
jsonify compatibility

### ISSUE THREAD

**Issue by hut8** [dcrosta/flask-pymongo#62]
I've been playing around with Flask and MongoDB today and really like them. Thanks very much for making integrating Flask with PyMongo easier.

I'm really surprised at how hard it is to return JSON from a view method, considering that's the first thing I tried and really only thing I want to do for this project. If this is integrating PyMongo and Flask, shouldn't there be an equivalent to `flask.jsonify()` that works with BSON?

As you probably know, this won't work because jsonify can't deal with ObjectId:

``` python
@app.route('/search/<query>')
def search(query):
    events = mongo.db.contributions.find({
        '_user_lower' : query.lower()
    })
    events = { 'events': list(events) }
    return jsonify(**events)
```

[Akhenakh's awesome gist](https://gist.github.com/akhenakh/2954605) is working for me right now, but it seems like pymongo should offer this.

**Comment by dcrosta** [comment]
I'd suggest looking at http://api.mongodb.org/python/current/api/bson/json_util.html -- it contains a complete implementation for converting BSON (or rather, the PyMongo objects which represent BSON documents) to and from JSON.

Should be pretty straightforward to wrap this into a decorator or utility function. I'll accept a PR if you want to do the work :)
