### ISSUE TITLE
The "fork me" banner on the website blows up when browser width is reduced

### ISSUE THREAD

**Issue by txtsd** [dcrosta/flask-pymongo#69]
![screenshot](https://i.imgur.com/nx3sgav.png)

**Comment by dcrosta** [comment]
Hi @txtsd -- what browser/version/OS is this? I can't reproduce with recent Chrome/macOS, nor any of my iDevices.

**Comment by txtsd** [comment]
It doesn't happen anymore. It was Firefox, but it happened on Chrome too, at the time.
