### ISSUE TITLE
Please make serverSelectionTimeoutMS configurable as well

### ISSUE THREAD

**Issue by bjjl** [dcrosta/flask-pymongo#72]
Subject says it all. Thanks much! :)

**Comment by jakubczaplicki** [comment]
+1

Even after setting 
```
    MONGO_CONNECT_TIMEOUT_MS = 1000
    MONGO_SOCKET_TIMEOUT_MS = 1000
```
PyMongo will still wait default 30 sec until `pymongo.errors.ServerSelectionTimeoutError` occurs.

Tested in Flask-PyMongo==0.4.1.

**Comment by matt-snider** [comment]
:+1:  

Had the same issue. Hanging the server/worker for 30 seconds on loss of connectivity makes this unusable in production.

**Comment by dcrosta** [comment]
Added in #80, will be part of a forthcoming 0.5.0 release.
