### ISSUE TITLE
Pass "connect=False" to MongoClient by default in PyMongo 3+

### ISSUE THREAD

**Issue by ajdavis** [dcrosta/flask-pymongo#87]
Hi Dan! First, a little background: MongoClient is not fork-safe. Programs that fork should create their MongoClients *after* forking. If that's not possible, the best workaround is to call ``MongoClient(connect=False)``, then fork, then start using the MongoClient.

A user asks how to pass "connect=False" to MongoClient with flask-pymongo:

http://stackoverflow.com/questions/41905472/pymongo-create-mongoclient-with-connect-false-or-create-client-after-forking

Is this currently possible?

I propose *always* passing "connect=False" to MongoClient in PyMongo 3 and later in flask-pymongo. If users frequently follow the pattern that the StackOverflow user shows, then "connect=False" will save some trouble.

**Comment by ranman** [comment]
Hey @ajdavis -- I'm not sure @dcrosta is still monitoring this project. I have the ability to update it and I know we added the `MONGO_CONNECT` config variable last year. Are you proposing something like: 
Changing https://github.com/dcrosta/flask-pymongo/blob/master/flask_pymongo/__init__.py#L163 to have a default of False ? Currently it defaults to true.

**Comment by ajdavis** [comment]
Hi @ranman! First, thanks for the pointer to MONGO_CONNECT, I hadn't found that before. Second, yes, I propose setting it to False.

**Comment by dcrosta** [comment]
This will be addressed in Flask-PyMongo 2.0 -- please see #110 for the announcement and discussion. (The tl;dr is that Flask-PyMongo will just accept a URI and kwargs, and won't have all the buggy and complicated custom configuration stuff)

**Comment by dcrosta** [comment]
This is addressed in 2.0 by adding a note to documentation in d50af87351590b805202ea2465b40c2cf0a640a2
