### ISSUE TITLE
Why tz_aware is forced to true?

### ISSUE THREAD

**Issue by n8v-guy** [dcrosta/flask-pymongo#91]
This should be considered as harmful practice since it is better to store everything in naive format, but in UTC.

**Comment by dcrosta** [comment]
@n8v-guy I agree. The tz_aware setting was a poor choice I made very early on in this project, but I've been unable to change it without breaking backwards compatibility.

I'm planning a Flask-PyMongo 2.0 which _will_ break backwards compatibility, and won't default this to True. In the meantime, I suggest you set it to False explicitly for new applications using Flask-PyMongo.

**Comment by crosvera** [comment]
How do you set it to False?

Best regards.
