### ISSUE TITLE
about the 'auth_database' and 'DBNAME' problem

### ISSUE THREAD

**Issue by shmily-xiao** [dcrosta/flask-pymongo#94]
I use MongoDB3.0 and  Flask-PyMongo 0.5.1 and Python2.7

this is my DB config:
MONGO_HOST = '127.0.0.1'
MONGO_USERNAME = 'mongo'
MONGO_PASSWORD = 'xxxxxxx'
MONGO_PORT = 27017
MONGO_DBNAME = 'test'
MONGO_READ_PREFERENCE = 'SECONDARY_PREFERRED'
MONGO_REPLICA_SET = '27017'
MONGO_CONNECT_TIMEOUT_MS = 20000

I want to use 'test' DB(DBNAME = 'test'), but the program always tell me  ' Authentication failed'
I check the mongoDB's log, and found the message like this  " UserNotFound Could not find user mongo@test"
My user's information is in the 'admin' ,not in the 'test'.

Then I found the code in the file names '__init__.py' ,and the file is in the package named 'flask_pymongo'

code in 128 lines is :
`auth_database = 'admin'`

code in 165-166 lines is :
    `if key('DBNAME') in app.config:`
         `auth_database = app.config[key('DBNAME')]`

I mean,after that code the  'auth_database' is not I wanted.
I want the `auth_database='admin'` and `MONGO_DBNAME = 'test'`
They are different.
Can you  give us the config paramer  like ``MONGO_AUTH_DBNAME='admin'`?
Thanks

**Comment by dcrosta** [comment]
I may have introduced a bug in 0.5.1, but could you please test with `MONGO_AUTH_SOURCE` or the `authSource` parameter in the query string? The value for either of those should be "admin" in your case (or generally, the DB in which the user you're authenticating at resides). From my reading of https://docs.mongodb.com/manual/reference/connection-string/, it seems like this ought to work, unless something I've done in Flask-PyMongo is preventing it from working.

**Comment by shmily-xiao** [comment]
It is working now .
 `MONGO_AUTH_SOURCE = 'admin' `
 Thinks a lot.
